- gz_topic_name: /camera/image
  ros_topic_name: /x500/camera/image_raw
  gz_type_name: gz.msgs.Image
  ros_type_name: sensor_msgs/msg/Image
  direction: GZ_TO_ROS

- gz_topic_name: /camera/camera_info
  ros_topic_name: /x500/camera/camera_info
  gz_type_name: gz.msgs.CameraInfo
  ros_type_name: sensor_msgs/msg/CameraInfo
  direction: GZ_TO_ROS

- gz_topic_name: /world/france/model/x500_mono_cam_down_0/link/camera_link/sensor/camera/image
  ros_topic_name: /drone/down_camera/image_raw
  gz_type_name: gz.msgs.Image
  ros_type_name: sensor_msgs/msg/Image
  direction: GZ_TO_ROS

- gz_topic_name: /world/france/model/x500_mono_cam_down_0/link/camera_link/sensor/camera/camera_info
  ros_topic_name: /drone/down_camera/camera_info
  gz_type_name: gz.msgs.CameraInfo
  ros_type_name: sensor_msgs/msg/CameraInfo
  direction: GZ_TO_ROS

# Additional mappings for other worlds/models (ELEC330Campus / x500_depth_survey)
- gz_topic_name: /world/ELEC330Campus/model/x500_mono_cam_down_0/link/camera_link/sensor/camera/image
  ros_topic_name: /drone/down_camera/image_raw
  gz_type_name: gz.msgs.Image
  ros_type_name: sensor_msgs/msg/Image
  direction: GZ_TO_ROS

- gz_topic_name: /world/ELEC330Campus/model/x500_mono_cam_down_0/link/camera_link/sensor/camera/camera_info
  ros_topic_name: /drone/down_camera/camera_info
  gz_type_name: gz.msgs.CameraInfo
  ros_type_name: sensor_msgs/msg/CameraInfo
  direction: GZ_TO_ROS

- gz_topic_name: /world/ELEC330Campus/model/x500_depth_survey/link/camera_link/sensor/camera/image
  ros_topic_name: /drone/down_camera/image_raw
  gz_type_name: gz.msgs.Image
  ros_type_name: sensor_msgs/msg/Image
  direction: GZ_TO_ROS

- gz_topic_name: /world/ELEC330Campus/model/x500_depth_survey/link/camera_link/sensor/camera/camera_info
  ros_topic_name: /drone/down_camera/camera_info
  gz_type_name: gz.msgs.CameraInfo
  ros_type_name: sensor_msgs/msg/CameraInfo
  direction: GZ_TO_ROS
  
- gz_topic_name: /camera/depth_image
  ros_topic_name: /x500/depth/image_raw
  gz_type_name: gz.msgs.Image
  ros_type_name: sensor_msgs/msg/Image
  direction: GZ_TO_ROS

- gz_topic_name: /clock
  ros_topic_name: /clock
  gz_type_name: gz.msgs.Clock
  ros_type_name: rosgraph_msgs/msg/Clock
  direction: GZ_TO_ROS
  
- gz_topic_name: /scan/points
  ros_topic_name: /x500/scan/points
  gz_type_name: gz.msgs.PointCloudPacked
  ros_type_name: sensor_msgs/msg/PointCloud2
  direction: GZ_TO_ROS
