- gz_topic_name: /world/liverpool/model/x500_depth_0/link/camera_link/sensor/IMX214/image
  ros_topic_name: /x500/camera/image_raw
  gz_type_name: gz.msgs.Image
  ros_type_name: sensor_msgs/msg/Image
  direction: GZ_TO_ROS

- gz_topic_name: /world/liverpool/model/x500_depth_0/link/camera_link/sensor/IMX214/camera_info
  ros_topic_name: /x500/camera/camera_info
  gz_type_name: gz.msgs.CameraInfo
  ros_type_name: sensor_msgs/msg/CameraInfo
  direction: GZ_TO_ROS
  
- gz_topic_name: /depth_camera
  ros_topic_name: /x500/depth/image_raw
  gz_type_name: gz.msgs.Image
  ros_type_name: sensor_msgs/msg/Image
  direction: GZ_TO_ROS
  
- gz_topic_name: /depth_camera/points
  ros_topic_name: /x500/depth/points
  gz_type_name: gz.msgs.PointCloudPacked
  ros_type_name: sensor_msgs/msg/PointCloud2
  direction: GZ_TO_ROS
