/**:
  ros__parameters:
    use_sim_time: true
    fcu_url: "udp://:14540@localhost:14557"

/mavros/local_position:
  ros__parameters:
    frame_id: "odom"
    tf:
      send: true
      frame_id: "odom"
      child_frame_id: "base_link"
      
/mavros/global_position:
  ros__parameters:
    tf:
      send: false

/mavros/obstacle:
  ros__parameters:
    mav_frame: "BODY_FRD"
